#! /bin/bash

unamestr=$(uname)

if [[ "$unamestr" == 'Linux' ]] ; then
  # other stuff here
  echo "Saving homebrew lists: SKIPPING"
elif [[ "$unamestr" == 'Darwin' ]] ; then
  command -v brew >/dev/null 2>&1 || { echo >&2 "I require brew but it's not installed.  Aborting."; exit 1; }
  brew list > ~/.dotfiles/homebrew/brew.txt
  brew cask list > ~/.dotfiles/homebrew/cask.txt
fi
