#!/bin/bash

mkdir -p ~/.local/bin
mkdir -p ~/.config/fish

case $1 in
  '')
    stow -R --target="$HOME" home
    ;;
  --uninstall|-u)
    stow -D --target="$HOME" home
    ;;
  *)
    echo $"Usage: $0 [-u|--uninstall]"
    ;;
esac
