" Pathogen 

let g:pathogen_disabled = []

if !has('nvim')
    call add(g:pathogen_disabled, 'vim-airline')
endif

execute pathogen#infect()

" Simple tweaks
syntax on
filetype plugin indent on
set number
set nocompatible

" vim-go 
let g:go_fmt_command = "goimports"

" Neovim doesn't have python so we use vim-airline
if has('nvim')
  let g:airline_powerline_fonts = 1
endif

" Powerline if not neovim (nvim doesn't support powerline) 
if !has('nvim')
  python from powerline.vim import setup as powerline_setup
  python powerline_setup()
  python del powerline_setup
endif

" For solarized
"let g:solarized_termcolors=256
syntax enable
set background=dark
colorscheme solarized

" Source the vimrc file after saving it
if has("autocmd")
  autocmd bufwritepost .vimrc source $MYVIMRC
endif

" tab-settings
set ts=2 sts=2 sw=2 expandtab
