tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "railwaycat/emacsmacport"
# Download with resuming and segmented downloading
brew "aria2"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Generic library support script
brew "libtool"
# YAML Parser
brew "libyaml"
# Library for command-line editing
brew "readline"
# ODBC 3 connectivity for UNIX
brew "unixodbc"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Statistics utility to count lines of code
brew "cloc"
# Get, unpack, build, and install modules from CPAN
brew "cpanminus"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# GNU implementation of time utility
brew "gnu-time"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Improved top (interactive process viewer)
brew "htop"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Utility for managing network connections
brew "netcat"
# Port scanning utility for large networks
brew "nmap"
# Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
brew "prettier"
# Monitor data's progress through a pipe
brew "pv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Displays the differences between SQLite databases
brew "sqldiff"
# Analyze how space is allocated inside an SQLite file
brew "sqlite-analyzer"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# JavaScript package manager
brew "yarn"
# Download YouTube videos from the command-line
brew "youtube-dl"
# YAMAMOTO Mitsuharu's Mac port of GNU Emacs
cask "emacs-mac"
# Web browser
cask "firefox"
cask "font-fira-code"
cask "font-ibm-plex"
# Git interface focused on visual interaction
cask "gitup"
# Web browser
cask "google-chrome"
# Free and open-source media player
cask "iina"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Tool to prevent the system from going into sleep mode
cask "keepingyouawake"
# Git client
cask "sublime-merge"
# Open-source BitTorrent client
cask "transmission"
# Open-source code editor
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "DaisyDisk", id: 411643860
mas "Day One", id: 1055511498
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Wipr", id: 1320666476
mas "WireGuard", id: 1451685025
