tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Library for command-line editing
brew "readline"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get, unpack, build, and install modules from CPAN
brew "cpanminus"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Load/unload environment variables based on $PWD
brew "direnv"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# Distributed revision control system
brew "git"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU implementation of time utility
brew "gnu-time"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Generic library support script
brew "libtool"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Improved top (interactive process viewer)
brew "htop"
# Lightweight and flexible command-line JSON processor
brew "jq"
# YAML Parser
brew "libyaml"
# Fast Cross-Platform Package Manager
brew "micromamba"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Shell command parallelization utility
brew "parallel"
# Fast C/C++ prime number generator
brew "primesieve"
# Monitor data's progress through a pipe
brew "pv"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Maintained ctags implementation
brew "universal-ctags"
# Internet file retriever
brew "wget"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Programming language designed for robustness, optimality, and clarity
brew "zig"
# Application uninstaller
cask "appcleaner"
# E-books management software
cask "calibre"
# Voice and text chat software
cask "discord"
# Web browser
cask "firefox"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Git interface focused on visual interaction
cask "gitup"
# Web browser
cask "google-chrome"
# Free and open-source media player
cask "iina"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Jellyfin desktop client
cask "jellyfin-media-player"
# Tool to prevent the system from going into sleep mode
cask "keepingyouawake"
# Adaptive brightness for external displays
cask "lunar"
# Mesh VPN based on WireGuard
cask "tailscale"
# Open-source code editor
cask "visual-studio-code"
# Video communication and virtual meeting platform
cask "zoom"
