" vim-plug config {{{
call plug#begin('~/.local/share/vim/plugged')

" Vim enhancements
Plug 'AndrewRadev/splitjoin.vim'
Plug 'airblade/vim-gitgutter'
Plug 'airblade/vim-rooter'
Plug 'andymass/vim-matchup'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tommcdo/vim-lion'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'

call plug#end()
" }}}

" basic settings {{{
scriptencoding utf-8
syntax on
filetype plugin indent on

set autoindent
" set autoread
set background=dark
set backspace=indent,eol,start
set backupdir=~/.local/share/vim//,/tmp//
set breakindent
set clipboard^=unnamed,unnamedplus
set directory=~/.local/share/vim//,/tmp//
set hidden
set history=1000
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set list
set listchars=trail:·,extends:#,tab:▸·,nbsp:·
set mouse=a
set noerrorbells
set number
set ruler
set scrolloff=8
set shell=bash
set shortmess+=c
set showbreak=\\\\\
set showmatch
set smartcase
set synmaxcol=300
set tabstop=2 sts=2 sw=2 expandtab
set tags^=./.git/tags;
set title
set wildmenu

colorscheme habamax

" keymappings {{{
let g:mapleader = "\<Space>"

cmap w!! w !sudo tee % >/dev/null
nnoremap <leader>W  :%s/\s\+$<cr>
nnoremap <C-p>     :bprev<cr>
nnoremap <C-n>     :bnext<cr>

inoremap jk <esc>
nnoremap Q <nop> " don't enter ex mode accidentally
" }}}

" junegunn/fzf {{{
nnoremap <C-t> :Files<cr>
nnoremap <leader>g :GFiles?<cr>
nnoremap <leader>b :Buffers<cr>
" }}}
