set -q fish_vars_set; or set_up_fish

# set -gx NODE_OPTIONS --openssl-legacy-provider

if command -sq asdf
    # Generated by:
    # echo -e "\nsource "(brew --prefix asdf)"/libexec/asdf.fish" >> ~/.config/fish/config.fish
    source /opt/homebrew/opt/asdf/libexec/asdf.fish
else if test -e ~/.asdf/asdf.fish
    source ~/.asdf/asdf.fish
end
