if not set -q fish_vars_set
    set -U fish_vars_set 1

    set_up_fish
end

if command -sq asdf
    # Generated by:
    # echo -e "\nsource "(brew --prefix asdf)"/libexec/asdf.fish" >> ~/.config/fish/config.fish
    source /opt/homebrew/opt/asdf/libexec/asdf.fish
else if test -e ~/.asdf/asdf.fish
    source ~/.asdf/asdf.fish
end
