#!/bin/sh

# needs some work
alias rubo="git diff --diff-filter=ACMR --name-only -z origin/master -- \*.{rb,rake} | xargs -0 bundle exec rubocop -R -D"
alias rubox='rubocop -a -R -D **/*.{rb,rake}'
alias al="ag --files-with-matches --smart-case"
alias vt="xargs -o nvim -p"
alias vi="nvim"
alias nyan="telnet nyancat.dakko.us"
alias nw='tmux new-window'
alias rs='rails s -b 127.0.0.1'
alias git-hidden="git ls-files -v | grep '^h'"
alias tmate='COMPATIBILITY=1 tmate'
alias vu='vagrant up'
alias vp='vagrant provision'
alias vss='vagrant status'
alias vd='vagrant destroy'
alias vh='vagrant halt'
alias vssh='vagrant ssh'
alias guposs='git_up_oss'
alias zshrc='nvim ~/.zshrc'
alias vd='cd ~/OSS/huddle/app/assets/javascripts/visual_directory'
