#!/bin/bash
set -eu
play-yt() {
  youtube-dl \
    --default-search 'ytsearch' \
    --no-playlist \
    -f bestaudio \
    --output '/tmp/%(title)s.%(ext)s' \
    --extract-audio --audio-format mp3 --keep-video \
    --exec 'mpv {}' \
    "$1"
}

git_up_oss() {
  base=~/OSS
  repos=(huddle kit puppet_modules tasks)

  pushd

  for repo in "${repos[@]}"; do
    echo updating "$base/$repo"
    cd "$base/$repo"; git up
  done

  popd
}
set +eu
