# zshrc

export DOTFILES_PATH=$HOME/.dotfiles
export ZSH=$DOTFILES_PATH/zsh/oh-my-zsh

ZSH_THEME='lambda'

# Set case sensitivity
# CASE_SENSITIVE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# plugins=(git ruby tmux osx bundler)
plugins=(gitfast ruby rake-fast tmux osx safe-paste golang fasd fzf)

# export ZSH_TMUX_AUTOSTART=true
source "$ZSH/oh-my-zsh.sh"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# User configuration
setopt HIST_IGNORE_ALL_DUPS

export rvm_ignore_dotfiles=yes

# as per zsh-install notes
unalias run-help
autoload run-help
export HELPDIR=/usr/local/share/zsh/help

export GOPATH=$HOME/Lang/go

source "$DOTFILES_PATH/zsh/alias"
source "$DOTFILES_PATH/zsh/custom-functions"

if [ -z "$COMPATIBILITY" ]; then
  source "$DOTFILES_PATH/zsh/promptline.sh"
else
  true
  # To make FZF not try to open a tmux split, because of
  # incompatibilityes with tmate
  # export FZF_TMUX=0
  # source $DOTFILES_PATH/zsh/promptline_compat.sh
fi

# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# _path_prepend $ANACONDA_PATH/bin
