# zshrc

export DOTFILES_PATH=$HOME/.dotfiles
export ZSH=$DOTFILES_PATH/zsh/oh-my-zsh

ZSH_THEME='lambda'

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git ruby tmux osx)
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# User configuration
setopt HIST_IGNORE_ALL_DUPS

if [ -n "$TMUX" ] && [[ "$TMUX" == *"tmate"* ]]; then
  # echo 'tmate mode'
  export COMPATIBILITY=1
fi

# as per zsh-install notes
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# anaconda is installed here
 PATH=$HOME/.local/bin:$HOME/anaconda3/bin:$PATH

source $DOTFILES_PATH/zsh/alias

unamestr=$(uname)
if [[ "$unamestr" == 'Darwin' ]] ; then
  # Only do this if we're on OSX
  POWERLINE_ROOT=$HOME/.local/lib/python3.4/site-packages
  POWERLINE_ZSH=$POWERLINE_ROOT/powerline/bindings/zsh/powerline.zsh
  export POWERLINE_TMUX=$POWERLINE_ROOT/powerline/bindings/tmux/powerline.conf
  if [ -z "$COMPATIBILITY" ]; then
    powerline-daemon -q
    source $POWERLINE_ZSH
  fi
fi

USE_RVM=1
if [ $USE_RVM ]; then
  # export PATH=$HOME/.rvm/bin:$PATH
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
else
  export PATH=$HOME/.rbenv/bin:$PATH
  eval "$(rbenv init -)"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
